var data=[$scope.spouseOption
,$scope.houseOption
,$scope.healthOption
,$scope.hospitalOption
,$scope.diseaseOption
,$scope.spouseDetails
,$scope.fy
,$scope.annualSalary
,$scope.grossAnnualIncome
,$scope.superBalance
,$scope.cashAtBank
,$scope.salarySacrifice
,$scope.ncc
,$scope.superTaxRate
,$scope.thp 
,$scope.insurancePremium
,$scope.investmentReturn
,$scope.variableFee
,$scope.fixedFee
,$scope.employerContributionLevel
,$scope.inflation
,$scope.wageIncrease
,$scope.rateOfReturn
,$scope.retirementAge
,$scope.pensionStart
,$scope.showPensionOption
,$scope.pensionDrawdownBase
,$scope.target
,$scope.annualSalarySpouse
,$scope.superBalanceSpouse
,$scope.salarySacrificeSpouse
,$scope.insurancePremiumSpouse
,$scope.investmentReturnSpouse
,$scope.variableFeeSpouse
,$scope.fixedFeeSpouse
,$scope.employerContributionLevelSpouse
,$scope.inflationSpouse
,$scope.wageIncreaseSpouseSlider
,$scope.retirementAgeSpouse
,$scope.pensionStartSpouse
,$scope.showPensionOptionSpouse
,$scope.pensionDrawdownBaseSpouse
,$scope.fundTypeA
,$scope.fundTypeB
,$scope.fundsOb
,$scope.fundsOb
,$scope.investOptions
,$scope.fundNameA
,$scope.contributionFeeA
,$scope.adminFeeA
,$scope.indirectCostRationA
,$scope.fundNameB
,$scope.contributionFeeB
,$scope.adminFeeB
,$scope.indirectCostRationB
,$scope.homeMortgage
,$scope.investmentPropertyMortgage
,$scope.creditCardDebt
,$scope.carLoan
,$scope.personalLoan
,$scope.otherLoan
,$scope.numChildren
,$scope.ageChildren1
,$scope.ageChildren2
,$scope.ageChildren3
,$scope.ageChildren4
,$scope.ageChildren5
,$scope.funeralCost
,$scope.educationExpensePerYearPerChild
,$scope.familyLivingCostPerYear
,$scope.ageSpouse
,$scope.yesornoarray[$scope.spouseWorkOption]
,$scope.spouseSalary
,$scope.yesornoarray[$scope.buyOption]
,$scope.valueOfNewProperty
,$scope.moneyToBeBorrowed
,$scope.ecLife
,$scope.ecTPD
,$scope.ecIP
,$scope.ecTrauma
,$scope.sickLeaves
,$scope.homeValue
,$scope.homeContents
,$scope.vehicleCost
,$scope.investmentProperty
,$scope.bankAssets
,$scope.listedInvestment
,$scope.marginLoans
,$scope.allocatedPension
,$scope.otherInvestment
,$scope.netRentalIncome
,$scope.otherIncome
,$scope.pensionIncome
,$scope.nra
,$scope.tfp
,$scope.nrp
,$scope.beforeTTR
,$scope.initialInvestmentAmount
,$scope.australianShares1Slider
,$scope.internationalShares1
,$scope.internationalSharesHedged1
,$scope.usShares1
,$scope.australianBonds1
,$scope.internationalBondsHedged1
,$scope.cash1
,$scope.australianListedProperty1
,$scope.internationalListedProperty1
,$scope.asset1Total
,$scope.yesornoarray[$scope.alterOption]
,$scope.alterYear
,$scope.australianShares2
,$scope.internationalShares2
,$scope.internationalSharesHedged2
,$scope.usShares2
,$scope.australianBonds2
,$scope.internationalBondsHedged2
,$scope.cash2
,$scope.australianListedProperty2
,$scope.internationalListedProperty2
,$scope.begnYearInvestment
,$scope.numChildren
,$scope.contStartYear
,$scope.portfolioListOb[spPort]
,$scope.c1Name
,$scope.yesornoarray[$scope.studyingOption1]
,$scope.schoolYear1
,$scope.schoolDuration1
,$scope.schoolObjectsShow[schoolArray[0]].name
,$scope.majorFeesListObj[majorSelectedArray[0]].name

,$scope.c2Name
,$scope.yesornoarray[$scope.studyingOption2]
,$scope.schoolYear2
,$scope.schoolDuration2
,$scope.schoolObjectsShow[schoolArray[1]].name
,$scope.majorFeesListObj[majorSelectedArray[1]].name

,$scope.c3Name
,$scope.yesornoarray[$scope.studyingOption3]
,$scope.schoolYear3
,$scope.schoolDuration3
,$scope.schoolObjectsShow[schoolArray[2]].name
,$scope.majorFeesListObj[majorSelectedArray[2]].name

,$scope.c4Name
,$scope.yesornoarray[$scope.studyingOption4]
,$scope.schoolYear4
,$scope.schoolDuration4
,$scope.schoolObjectsShow[schoolArray[3]].name
,$scope.majorFeesListObj[majorSelectedArray[3]].name

,$scope.c5Name
,$scope.yesornoarray[$scope.studyingOption5]
,$scope.schoolYear5
,$scope.schoolDuration5
,$scope.schoolObjectsShow[schoolArray[4]].name
,$scope.majorFeesListObj[majorSelectedArray[4]].name

,$scope.c6Name
,$scope.yesornoarray[,$scope.studyingOption6]
,$scope.schoolYear6
,$scope.schoolDuration6
,$scope.schoolObjectsShow[schoolArray[5]].name
,$scope.majorFeesListObj[majorSelectedArray[5]].name

]